### ISSUE TITLE
Incompatible with facebox v0.4

### ISSUE THREAD

**Issue by robmarkcole** [RdeLange/robinvision#2]
I'm afraid that compatibility with the HA facebox component is broken in https://github.com/robmarkcole/HASS-Machinebox-Facebox/releases/tag/v0.4 as the `bounding_box` and image `id` of a face are now [explicitly parsed](https://github.com/robmarkcole/HASS-Machinebox-Facebox/blob/ee96dfb28a3215d4afac86561d9119a3d48112ac/custom_components/image_processing/facebox.py#L60) by `parse_faces()`. I see that `face_recognition.face_locations` does return bounding boxes so this could be implemented. `id` could be anything.

Note that a workaround is to [comment out](https://github.com/robmarkcole/HASS-Machinebox-Facebox/blob/ee96dfb28a3215d4afac86561d9119a3d48112ac/custom_components/image_processing/facebox.py#L73) `face[ATTR_BOUNDING_BOX] = entry['rect']` and `face[ATTR_IMAGE_ID] = entry['id']`

**Comment by RdeLange** [comment]
Thanks for pointing out. using the face_recognition.face_locations should do the trick indeed. When I have some time I will get that squeezed in.

**Comment by RdeLange** [comment]
Hi, now included the bounding box and included a dummy id to get it work. Hopefully this works now. I am currently having some problems to test is with HA myself

**Comment by robmarkcole** [comment]
Works, nice!
